### PR TITLE
Fix allauth reset password bug

### PR DESCRIPTION
**Pull request by LanceMoe**

### CODE REVIEW

**Comment by LanceMoe** [comment]
When the project uses allauth, the reset password email will generate an incorrect token(because allauth use it self token_generator), which prevents the user from resetting the password.

This is a serious problem, please merge as soon as possible. Thanks!

**Comment by LanceMoe** [comment]
And, I provide a temporary workaround:
```python
from dj_rest_auth.serializers import \
    PasswordResetSerializer as DefaultPasswordResetSerializer

...

class PasswordResetSerializer(DefaultPasswordResetSerializer):
    '''Workaround'''

    def save(self):
        if 'allauth' in settings.INSTALLED_APPS:
            from allauth.account.forms import default_token_generator
        else:
            from django.contrib.auth.tokens import default_token_generator
        request = self.context.get('request')
        # Set some values to trigger the send_email method.
        opts = {
            'use_https': request.is_secure(),
            'from_email': getattr(settings, 'DEFAULT_FROM_EMAIL'),
            'request': request,
            'token_generator': default_token_generator,
        }

        opts.update(self.get_email_options())
        self.reset_form.save(**opts)
```

Then add in `settings.py`:
```python
REST_AUTH_SERIALIZERS = {
    ...
    # workaround
    'PASSWORD_RESET_SERIALIZER': 'ucenter.serializers.PasswordResetSerializer',
    ...
}
```

**Comment by LanceMoe** [comment]
I found another problem. Because allauth uses base36 to encrypt uid, but django uses base64 by default, it will prompt `Invalid value` when resetting the password. This problem can be solved by using the commit I just submitted.

**Review by sandy2008 — APPROVED** [review]

**Comment by iMerica** [comment]
This change is in the latest release
https://pypi.org/project/dj-rest-auth/

**Comment by steverecio** [comment]
Which version of allauth was this tested against? Running dj-rest-auth==2.1.9 and django-allauth==0.45.0 gives me the following error on [this line](https://github.com/iMerica/dj-rest-auth/blob/master/dj_rest_auth/forms.py#L50):

`django.urls.exceptions.NoReverseMatch: Reverse for 'password_reset_confirm' not found. 'password_reset_confirm' is not a valid view function or pattern name.`

**Comment by LanceMoe** [comment]
> Which version of allauth was this tested against? Running dj-rest-auth==2.1.9 and django-allauth==0.45.0 gives me the following error on [this line](https://github.com/iMerica/dj-rest-auth/blob/master/dj_rest_auth/forms.py#L50):
> 
> `django.urls.exceptions.NoReverseMatch: Reverse for 'password_reset_confirm' not found. 'password_reset_confirm' is not a valid view function or pattern name.`

Please see faq no.2 first: https://dj-rest-auth.readthedocs.io/en/latest/faq.html

**Comment by psacawa** [comment]
This is broken, at least in the demo project. When I try to reset a password in the demo, I get the follow stacktrace
```
Internal Server Error: /dj-rest-auth/password/reset/
Traceback (most recent call last):
  File "/home/psacawa/.pyenv/versions/garbage/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/psacawa/.pyenv/versions/garbage/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/psacawa/.pyenv/versions/garbage/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/psacawa/.pyenv/versions/garbage/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/psacawa/.pyenv/versions/garbage/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/psacawa/.pyenv/versions/garbage/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/psacawa/.pyenv/versions/garbage/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/psacawa/.pyenv/versions/garbage/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/psacawa/.pyenv/versions/garbage/lib/python3.9/site-packages/dj_rest_auth/views.py", line 250, in post
    serializer.save()
  File "/home/psacawa/.pyenv/versions/garbage/lib/python3.9/site-packages/dj_rest_auth/serializers.py", line 257, in save
    self.reset_form.save(**opts)
  File "/home/psacawa/.pyenv/versions/garbage/lib/python3.9/site-packages/dj_rest_auth/forms.py", line 42, in save
    path = reverse(
  File "/home/psacawa/.pyenv/versions/garbage/lib/python3.9/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/psacawa/.pyenv/versions/garbage/lib/python3.9/site-packages/django/urls/resolvers.py", line 694, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'password_reset_confirm' with arguments '('1', 'aqgote-811cbd70336d82d5c64fc32276480a1d')' not found. 1 pattern(s) tried: ['password-reset/confirm/(?P<uidb64>[0-9A-Za-z_\\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$']
[27/Jul/2021 20:27:14] "POST /dj-rest-auth/password/reset/ HTTP/1.1" 500 135469
```

**Comment by psacawa** [comment]
Indeed the generated reset token has a form like `aqgql8-43444d5efff4898b06c1938a01fd8d9d`. The second part has 32 characters length, while the demo project and docs use a regex that matches up to 20 chars.

**Pull request merged**
