### PR TITLE
Add Compatibility for django-allauth v0.55.2

### LINKED ISSUE #534: Error: "allauth needs to be added to INSTALLED_APPS" after upgrading to django-allauth v0.55.0
Due to a backwards-incompatible change in django-allauth's new v0.55.0, dj_rest_auth does not work with the newest version of allauth. django-allauth's [v0.55.0 does NOT have a function "email_address_exists"](https://github.com/pennersr/django-allauth/blob/main/ChangeLog.rst#backwards-incompatible-changes) in `allauth/utils.py`  which is what is causing dj_rest_auth to throw an error in the first place. 

How I reproduced:
1. In my Django project, I installed the latest versions of both allauth and dj-rest-auth with `pip install django-allauth dj-rest-auth`.
2. Add the appropriate apps inside `INSTALLED_APPS`. For reference, I added this to mine: 
```py
[
...
'django.contrib.sites',
'allauth',
'allauth.account',
'allauth.socialaccount',
'allauth.socialaccount.providers.google',

'dj_rest_auth',
'dj_rest_auth.registration',
...
]
```
3. In one of my apps' `views.py`, I imported `from dj_rest_auth.registration.views import SocialLoginView`.
4. After running `py manage.py makemigrations` or `py manage.py runserver`, etc... I received 
```bash
ImportError: allauth needs to be added to INSTALLED_APPS
```
I tried:
- downgrading to django-allauth v0.54.0 and the error went away

The error comes from:
`dj_rest_auth/registration/serializers.py`

The expected output should be an errorless migration, but instead I cannot interact with any parts of my application

I created a minimal Django project with the same configurations and pip package versions that I tested above:
https://github.com/brandon-kong/dj_rest_auth_issue

### PR DESCRIPTION
**Pull request by Dresdn**
This addresses necessary updates and refactoring for compatibility with django-allauth version 0.55.2.

Fixes #534

### CODE REVIEW

**Comment by Dresdn** [comment]
To the reviewers:

Note that this does drop Django 2.2 support, bumps python min to 3.6, Django min to 3.2, and DRF min to 3.13. I did set the min allauth version to 0.55.2 since 0.55.0 introduced all the API changes and there were quick releases after to fix things.

**Comment by Dresdn** [comment]
Hey @iMerica - Could you take a look at this? Issue #534 is causing issues with the changes `django-allauth` made, and there are now 3 PRs open.

I know I'm biased, but looking at the different PRs, I think this is the most complete, as we do need to update the dependency requirements.

**Review by iMerica — APPROVED** [review]

**Comment by iMerica** [comment]
Thanks for tagging me. I sometimes miss GitHub notifications.

**Comment by Dresdn** [comment]
Thanks for all the effort!

**Comment by alexei** [comment]
@Dresdn @iMerica I appreciate your working on this. What are the plans to releasing the changes?

**Comment by iMerica** [comment]
Just released @alexei  👍

**Comment by alexei** [comment]
Great, thanks!

**Pull request merged**
