### PR TITLE
Convert allauth's OAuth2Error to serializer validation error

### PR DESCRIPTION
**Pull request by samhita-alla**
Signed-off-by: Samhita Alla <aallasamhita@gmail.com>

Hopefully, this PR fixes the 500 server error that pops up when the "code" given for GitHub authentication is invalid.

Screenshot 2021-12-10 at 12 30 02 PM
Screenshot 2021-12-10 at 12 32 36 PM

### CODE REVIEW

**Comment by tanmayag78** [comment]
Is there any update on this?

**Comment by pandafy** [comment]
Bumping this! 😄

**Comment by legalimpurity** [comment]
Bumping this!

**Comment by okapies** [comment]
I appreciate it if you could merge it.

**Review by iMerica — APPROVED** [review]

**Comment by iMerica** [comment]
this is fixed in a recently merged PR

**Pull request closed without merging**
